# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # wyłączone reguły generujące info/warn w obecnej fazie projektu
    # (będziemy je wdrażać stopniowo)
    # - avoid_print: false
    # - prefer_single_quotes: true

    # zignoruj przestarzałe i drażliwe reguły
    always_use_package_imports: false
    avoid_classes_with_only_static_members: false
    constant_identifier_names: false
    prefer_final_fields: false
    prefer_final_locals: false
    library_private_types_in_public_api: false
    use_key_in_widget_constructors: false
    deprecated_member_use_from_same_package: false

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
